from setuptools import setup, find_packages

setup(name='pocket-change',
      version='0.0.4',
      author='Silas Ray',
      author_email='silas.ray@nytimes.com',
      license='Apache2.0',
      url='http://pocket-change.readthedocs.org/',
      description='The web front end for Sneeze and Pocket',
      long_description='The web front end for the Sneeze nose plugin test result reporting tool.',
      classifiers=['Development Status :: 4 - Beta',
                   'Intended Audience :: Information Technology',
                   'Topic :: Software Development :: Quality Assurance',
                   'Topic :: Software Development :: Testing'],
      packages=find_packages(),
      package_dir={'pocket_change' : 'pocket_change'},
      package_data={'pocket_change' : ['static/*', 'ui/templates/*']},
      include_package_data=True,
      install_requires=['sneeze-pocket',
                        'Flask',
                        'Flask-RESTful',
                        'Flask-SQLAlchemy',
                        'passlib',
                        'flask-login'])
